language: python
python:
  - "2.7"
install:
  - git clone https://github.com/tabatkins/bikeshed.git
  - pip install --editable $PWD/bikeshed
  - pip install docutils
  - bikeshed update
script:
  - bash .deploy/deploy.sh
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
  local-dir: out
